### ISSUE TITLE
ImportError: cannot import name 'reCaptchaBypasser' from 'pypasser' 

### ISSUE THREAD

**Issue by roboes** [xHossein/PyPasser#4]
When I try to run the following code:

`from pypasser import reCaptchaBypasser`

I get this error: "ImportError: cannot import name 'reCaptchaBypasser' from 'pypasser'"

How to solve it? Thanks!

**Comment by robertog09** [comment]
I just noticed I was reading a [non-updated version of the documentation](https://github.com/xHossein/PyPasser/commit/9bb43b6824a65ed916315e539c5a4b248b54fe13#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5). Thanks!
